# Generated by Django 5.0.7 on 2024-07-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='categories',
            new_name='category',
        ),
    ]
